# GitHub Actions CI/CD Pipeline for MedGuardian Discord Bot
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm install
    
    - name: Verify installation
      run: |
        echo "Node.js version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Dependencies installed successfully!"
    
    - name: Run linter (if configured)
      run: npm run lint
      continue-on-error: true
    
    - name: Run tests (if available)
      run: npm test
      continue-on-error: true
    
    - name: Check code formatting (if configured)
      run: npm run format:check
      continue-on-error: true

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run security audit
      run: npm audit --audit-level moderate
      continue-on-error: true
