# GitHub Actions CI/CD Pipeline for MedGuardian Discord Bot
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
    
    - name: Run linter
      run: |
        if npm list eslint > /dev/null 2>&1; then
          npm run lint
        else
          echo "Linter not configured, skipping..."
        fi
      continue-on-error: true
    
    - name: Run tests
      run: |
        if [ -f "test" ] || [ -d "tests" ] || grep -q "test" package.json; then
          npm test
        else
          echo "No tests found, skipping..."
        fi
      continue-on-error: true
    
    - name: Check code formatting
      run: |
        if npm list prettier > /dev/null 2>&1; then
          npm run format:check
        else
          echo "Prettier not configured, skipping..."
        fi
      continue-on-error: true

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run security audit
      run: npm audit --audit-level moderate
      continue-on-error: true
